languageCode = 'it-IT'
title = 'Ulisse wiki'


[module]
[[module.imports]]
path = 'github.com/McShelby/hugo-theme-relearn'

[params]
themeVariant = "ulisse"
editURL = "https://github.com/UlisseLab/wiki/edit/main/content/"

[outputs]
home = ["HTML", "RSS", "PRINT"]
section = ["HTML", "RSS", "PRINT"]
page = ["HTML", "RSS", "PRINT"]
